#!/usr/bin/env ruby
# frozen_string_literal: true

# Exit cleanly from an early interrupt
Signal.trap("INT") { exit 1 }

require "modulizer"
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = """
  Modulizer: a ruby gem that modulize the web pages
  author: dave wu (eyaswoo@163.com)
  Sept. 2016 MIT

  Usage:
  $> modulizer [options]
  """

  opts.on("-e", "--entry ENTRY_FILE", "input file, normally html") do |e|
    options[:input] = e
  end

  opts.on("-o", "--output OUTPUT_FILE", "output file, normally js. if not provided, output to stdout") do |o|
    options[:output] = o
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

mod_file = options[:input]
raise "valid input module file is required" unless mod_file

result = Modulizer::Dummy.compile mod_file

if options[:output].nil?
  puts result
else
  File.write(options[:output], result)
end
